project:
  type: book

book:
  title: "Jackknife Variance Estimator for Datasets Containing Multiply Imputed Outcome Variables Under Uncongeniality: A Monte Carlo Simulation Study"
  chapters:
    - index.qmd
    - acknowledgments.qmd
    - abstract.qmd
    - background.qmd
    - methods.qmd
    - estimator.qmd
    - results.qmd
    - references.qmd
    - appendix.qmd
  sidebar: 
    title: " "

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-overflow: wrap
    df-print: paged
    

nocite: |
  @Wang_1998
