project:
  type: book

book:
  title: "Jackknife Variance Estimator for Datasets Containing Multiply Imputed Outcome Variables Under Uncongeniality: A Monte Carlo Simulation Study"
  author: "Ihsan E. Buker"
  date: "10/1/2022"
  chapters:
    - index.qmd
    - abstract.qmd
    - background.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

nocite: |
  @Wang_1998
